### ISSUE TITLE
Installation steps are not correct and not working on windows 10

### ISSUE THREAD

**Issue by sajjadG** [MolotovCherry/virtual-display-rs#42]
Downloaded the latest release (v0.3.1-rc1) installer zip from github and extracted the zip file. Following the README I tried to run `install-cert` but couldn't.
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/ac9e9ffa-379f-4a1f-89c0-220ef9c71035)

Needed to r-click on it and selecting properties then checking unlock before being able to run it. The unlocking had to be done for installer too before being able to run.
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/8b1d7628-e9cc-4530-9a09-5966f3097435)

After checking that GUI of windows showing certs (mentioned at the end of readme) the **Trusted Publishers** were empty!. 
Imported the cert manually in there then ran the installer but it failed to install and gave me this error windows:
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/2f096d9d-19c6-4858-b9d7-fc10deeec15d)

I'm testing on a windows 10 pro.

**Comment by sajjadG** [comment]
Double clicking on the certificate itself it opens a window like this which has the option of installing it:
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/62b27509-d68f-4820-b4ea-e2c51f018dfa)
This would be en easier option to install the cert I think if somebody prefers UI.

**Comment by sajjadG** [comment]
Trying portable version is not working either. I can't open control panel getting this error which I've reported before https://github.com/MolotovCherry/virtual-display-rs/issues/23
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/0726af8a-287c-4717-a3d2-d0da1ebfcc5c)

**Comment by sajjadG** [comment]
Should I see anything in device manager after installing portable version?
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/380602/f0dd2767-de02-4965-a793-2ff78a8e2df2)

**Comment by sajjadG** [comment]
Oh by the way, there's no monitor connected to this server right now. And it has a Nvidia Quadro M4000 installed.

**Comment by MolotovCherry** [comment]
> Needed to r-click on it and selecting properties then checking unlock before being able to run it. The unlocking had to be done for installer too before being able to run.

This is normal windows behavior for Windows when new versions of a file come out and it hasn't been downloaded enough. It does that for all (unsigned) programs universally, and goes away automatically in time.

> After checking that GUI of windows showing certs (mentioned at the end of readme) the Trusted Publishers were empty!.
Imported the cert manually in there then ran the installer but it failed to install and gave me this error windows:

Have you verified the certificates are installed to the correct locations (`Trusted Root Certification` and ` Trusted Publishers`) according to the instructions? Did you also make sure they're installed to the "Local Computer" store (not the current user certificates)?

It might be worth noting that, so far, every single case of this I've seen was because the certificates were not installed properly (which is why I have that troubleshooting section on how to make sure they're installed).

No idea why your `Trusted Publishers` is empty though, sounds like an interesting Windows bug! 😮 

> This would be en easier option to install the cert I think if somebody prefers UI.

The reason the instructions list this way is because you can visually see whether they're installed or not, which is a very important step for making sure it's installed.

Other than that, installation is pretty easy with the `bat` file, and doesn't require one to even go so far as use a gui.

> Trying portable version is not working either. I can't open control panel getting this error which I've reported before https://github.com/MolotovCherry/virtual-display-rs/issues/23

This is documented in https://github.com/MolotovCherry/virtual-display-rs/issues/23#issuecomment-1823923623 , not a problem with the driver / app. It's Windows / system configuration problem, and there's nothing I can do on my end about it (except make an app which doesn't require opengl).

> Should I see anything in device manager after installing portable version?

Uninstall every single virtual display driver related entry you see there (the ones marked as "unknown device"). There should be only 1 (which the driver installs itself).

**Comment by sajjadG** [comment]
I wish there was a installation method which could take care of certificate installation too. People could choose not to use it if the are concern about security and stuff :)

Thanks @MolotovCherry for your awesome work. I'm looking forward to the new GUI release.

**Comment by MolotovCherry** [comment]
> I wish there was a installation method which could take care of certificate installation too.
I suppose I'll look into making a separate option for that (if it's possible) 😢 If it was part of the installer that'd probably take care of security concerns. The more ideal solution is just that I have an official code signing certificate, which takes care of smartscreen/certificate installation completely. But those are quite expensive 😞
